### ISSUE TITLE
Minor service spelling issue and variable handling request

### ISSUE THREAD

**Issue by noybman** [moismailzai/wgjailr#2]
Your systemd "qbitorrent-nox" is spelled wrong. It should be "qbittorrent" (two t's). I forget it all the time myself.

As an aside, Since you feed wg the contents of the conf with a strip, why not grab the IP addresses of the DNS and the "client" from the wg-vpn.conf as well? Should these really be hardcoded variables in wgjailr?

Thanks for all the hard work. Im doing my best to learn namespaces and wireguard and hope to help contribute to the efforts.

**Comment by moismailzai** [comment]
Thanks for the catch! I wrote these to help illustrate the blog post but you're absolutely right, plenty of room to improve them, including what you've suggested. I'll find some time to update these if they're useful, or, feel free to send a PR!

**Comment by noybman** [comment]
I am finding them useful already. This has solved the issue of getting things working in their namespaces.

Maybe a simple task (I'm linux knowledgable but enough to be dangerous),  isn't it better to run the qbittorrent process (which is really a "user level app" as a user?).

I attempted to run it as a user, but it didnt work. I presume because it didnt have the userlevel to execute the wgjailr?

I want to get my port forwarding (on the torrent side) and I'll share any success I have. Again, thank you for everything.

**Comment by Best-HeyGman** [comment]
> Maybe a simple task (I'm linux knowledgable but enough to be dangerous), isn't it better to run the qbittorrent process (which is really a "user level app" as a user?).
> 
> I attempted to run it as a user, but it didnt work. I presume because it didnt have the userlevel to execute the wgjailr?

For this I have a solution. Had the same problem and solved it by adding another systemd service template which allows you to start qbittorrent as a normal user. Made a Pull Request:
https://github.com/moismailzai/wgjailr/pull/1
Hasn't been accepted yet. But here is my branch with the added systemd service (netns-vpn-qbittorrent-nox@.service):
https://github.com/Best-HeyGman/wgjailr/tree/user-specific-service


> As an aside, Since you feed wg the contents of the conf with a strip, why not grab the IP addresses of the DNS and the "client" from the wg-vpn.conf as well? Should these really be hardcoded variables in wgjailr?

I volunteer to do that. Wrote a lot of shell scripts lately, so writing the code should not take long. But testing will probably take some time.

**Comment by Best-HeyGman** [comment]
Alrigth @moismailzai @noybman 
the PR for the requested feature is ready: https://github.com/moismailzai/wgjailr/pull/3
I've tested it, but additional testing on different setups is always a good idea.

**Comment by noybman** [comment]
Thank you. I grabbed the new files on the new issue and will try them out.
We should close this issue since its really the spelling issue by itself. (commit service to main?)

**Comment by moismailzai** [comment]
Thanks to you both!
